name: Ejecutar pruebas de Python

on: [push] # Ejecutar el flujo de trabajo cuando se haga un push

jobs:
  build:
    runs-on: ubuntu-latest # El sistema operativo que se usará

    steps:
    - name: Configurar el entorno de Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12 # Cambia '3.x' por la versión de Python que necesites

    - name: Ejecutar pruebas
      run: pytest
      
