name: Ejecutar pruebas de Python

on:
  push:
    branches:
      - main  # Reemplaza 'main' con el nombre de tu rama principal

jobs:
  test:
    runs-on: ubuntu-latest # El sistema operativo que se usará

    steps:
    - name: Configurar el entorno de Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12 # Cambia '3.x' por la versión de Python que necesites

    - name: Instalar pytest
      run: pip install pytest
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Cambiasdirectorio del proyecto
      working-directory: ..  # Ruta al directorio raíz de tu proyecto
      run: ls -lah

      

    - name: Ejecutar pruebas
      working-directory: ..  # Ruta al directorio raíz de tu proyecto
      run: pytest ./tests/
      
      
